name: ultra_hardcore
version: '${project.version}'
main: scriptservice.ultra_hardcore.uhc
depend:
  - Apollo-Bukkit

commands:
  uhc:
    description: commande holder pour l'uhc
  scenarios:
    description: commande holder pour les scenarios
  sc:
    description: commande holder pour les scenarios
  scs:
    description: commande holder pour les scenarios